apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    logging:
      level:
        org.springframework: INFO
        org.springframework.cloud: DEBUG
    spring:
      cloud:
        dataflow:
          applicationProperties:
            stream:
              spring:
                cloud:
                  config:
                    uri: http://${SPRINGCONFIG_SERVICE_HOST}:${SPRINGCONFIG_SERVICE_PORT}
              management:
                metrics:
                  export:
                    prometheus:
                      enabled: true
                      rsocket:
                        enabled: true
                        host: prometheus-proxy
                        port: 7001
            task:
              spring:
                cloud:
                  config:
                    uri: ${SPRINGCONFIG_SERVICE_HOST}:${SPRINGCONFIG_SERVICE_PORT}
              management:
                metrics:
                  export:
                    prometheus:
                      enabled: true
                      rsocket:
                        enabled: true
                        host: prometheus-proxy
                        port: 7001
          grafana-info:
            url: 'http://192.168.39.145:30117'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
                    volumes: 
                      - name: nas
                        persistentVolumeClaim:
                          claimName: nas-pv-claim
                    volume-mounts:
                      - name: nas
                        mountPath: "/nas"
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

